### ISSUE TITLE
Does not work with pytest 5.0.1

### ISSUE THREAD

**Issue by attila123** [janschulz/pytest-error-for-skips#2]
After updating pytest to 5.0.1 (from 4.6.2), it fails with the following error if I use the command line option '--error-for-skips'.

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 213, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 257, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 278, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 72, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 81, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/_pytest/runner.py", line 169, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/pytest_error_for_skips.py", line 10, in pytest_runtest_makereport
INTERNALERROR>     if pytest.config.getoption('--error-for-skips'):
INTERNALERROR>   File "/path/to/my-project/.tox/py37/lib/python3.7/site-packages/_pytest/main.py", line 187, in __getattr__
INTERNALERROR>     warnings.warn(PYTEST_CONFIG_GLOBAL, stacklevel=2)
INTERNALERROR> pytest.PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure` (if you're a pytest plugin) instead.
```
Downgraded pytest to 4.6.4 because of this, and with 4.6.4 the warning is already there:
```
  /path/to/my-project/.tox/py37/lib/python3.7/site-packages/pytest_error_for_skips.py:10: PytestDeprecationWarning: the `pytest.config` global is deprecated.  Please use `request.config` or `pytest_configure` (if you're a pytest plugin) instead.
    if pytest.config.getoption('--error-for-skips'):
```
(Actually in pytest 5.0.x it would be still possible to change this error back to warning (see "#5402: PytestDeprecationWarning are now errors by default." at https://docs.pytest.org/en/latest/changelog.html).

**Comment by jayvdb** [comment]
While not a solution, use `-p no:warnings` to make this plugin work with pytest5 until it is patched
